### ISSUE TITLE
`ICESat2_Granule{:ATL06}` are returned by` find` without bounding boxes. 

### ISSUE THREAD

**Issue by alex-s-gardner** [evetion/SpaceLiDAR.jl#28]
`ICESat2_Granule{:ATL06}` are returned by `find` without bounding boxes. 

geotile = (min_x = 50.0, min_y = -88.0, max_x = 51.0, max_y = -87.0)
granules = find(:ICESat2, "ATL06", geotile, "005")

julia> granules[1].bbox
NamedTuple()

julia> granules[2].bbox
NamedTuple()

julia> granules[3].bbox
NamedTuple()

**Comment by evetion** [comment]
Yeah, I designed those granules with the idea to hold extra metadata, but haven't implemented it, also because the metadata differs per product and is sometimes costly to get.

There's `bounds` that will calculate the bounding box based on the data, but that requires opening the (local) .h5 file (and while ICESat-2 stores the bbox in the metadata, GEDI doesn't, so we need to iterate through all coordinates to find the bbox).

There's also `info`, which parses the metadata from the filename.

I do see that there's a Polygon that's returned from NASA Earthdata Search for each granule, so we could use that as well.

**Comment by alex-s-gardner** [comment]
Given that the earthdata search quarry is so fast we could keep things light and just remove the bbox. I'm not using it in my processing. Do you have a need?

**Comment by evetion** [comment]
I could use it, and it's faster than locally computing it. Also for saving all granules to a shapefile, this could work. Happy to make a PR for it.
